# Generated by Django 3.2.5 on 2021-07-04 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=50, verbose_name='관심사')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images')),
                ('phone_number', models.IntegerField(verbose_name='전화번호')),
                ('nickname', models.CharField(max_length=20, verbose_name='닉네임')),
                ('school', models.CharField(max_length=20, verbose_name='학교')),
                ('age', models.IntegerField(verbose_name='나이')),
                ('gender', models.CharField(max_length=20, verbose_name='성별')),
                ('goal', models.CharField(max_length=100, verbose_name='목표')),
                ('major', models.CharField(max_length=50, verbose_name='전공')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='자기 소개')),
                ('club', models.CharField(blank=True, max_length=150, null=True, verbose_name='동아리')),
                ('ask', models.CharField(blank=True, max_length=100, null=True, verbose_name='ask')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='answer')),
                ('follower', models.ManyToManyField(blank=True, related_name='follower', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('interest', models.ManyToManyField(blank=True, related_name='interests', to='yk.Interest')),
                ('report', models.ManyToManyField(blank=True, related_name='신고', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
