# Generated by Django 3.2.5 on 2021-07-06 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yk', '0005_answer_answeres_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answeres_at',
            new_name='answered_at',
        ),
    ]
