# Generated by Django 3.2.5 on 2021-07-13 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yk', '0008_auto_20210713_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='logitude',
            new_name='longitude',
        ),
    ]
