# Generated by Django 3.2.5 on 2021-07-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yk', '0009_rename_logitude_profile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='위치'),
        ),
    ]
